### ISSUE TITLE
unable to install erlang 19.0.1

### ISSUE THREAD

**Issue by nathany** [asdf-vm/asdf-erlang#12]
see https://github.com/asdf-vm/asdf/issues/82

**Comment by Stratus3D** [comment]
Interesting. So I see there was a 19.0.1 package released (http://erlang.org/pipermail/erlang-questions/2016-June/089665.html), but it appears as if it contains just Erlang 19. Since the package update is from an Erlang maintainer would expect any official version changes to be reflected on erlang.org.

I'm also not sure how to verify the minor version of an Erlang installation... `erl` only prints out the major version number.

**Comment by Stratus3D** [comment]
Note that the asdf-erlang install script downloads from erlang.org, so we will either have to wait until erlang.org is updated or change how asdf-erlang downloads erlang archives. I suppose we could download from the archive from GitHub.

**Comment by nathany** [comment]
That is very interesting. I wonder if "19.0" is grabbing the latest source already then. I don't know how asdf-erlang works.

This may be useful: 
* https://github.com/Homebrew/homebrew-core/commit/0232c3f3648ceb53787d7ca2c8b45ec38a9b1684
* https://github.com/c0b/docker-erlang-otp/blob/master/19/Dockerfile

**Comment by HashNuke** [comment]
Erlang.org isn't updated with internal releases. I think `19.0.1` is one such internal release. Some years ago I too was clueless about this and asked around. The staff responsible for Erlang.org clarified on Twitter about it - https://twitter.com/brucify/status/537240367239016448

As a result of that, I started compiling Erlang from tags when required. As for asdf-erlang, you can install the latest erlang from a tag if you like. The latest erlang as of this comment is `OTP-19.0.2` (source: https://github.com/erlang/otp/releases)

```
asdf install erlang ref:OTP-19.0.2
```

The `ref` may refer to a git commit sha or the tag or the branch. In this case the git tag. Some asdf plugins support it. asdf-erlang does.

Incase you prefer to compile erlang using a ref, then your `.tool-versions` also has to be changed to reflect the version. So the erlang version can be specified like the following:

```
erlang ref:OTP-19.0.2
```

@nathany Hope that helps. Closing this issue. But if this turns out not to be an internal release, please do let us know. We will come up with something to ensure that we pull from the latest release.

**Comment by nathany** [comment]
Thanks @HashNuke. Looks like I also need to update autoconf to switch from Erlang 18.3 to ref:OTP-19.0.2.

```
***************************************************
***************************************************
*** WARNING: System might fail to configure or
***          might be erroneously configured
***          since autoconf version 2.13 is used
***          instead of version 2.59!
***************************************************
***************************************************

=== running autoconf in lib

=== running autoconf in lib/common_test

=== running autoconf in lib/erl_interface
configure.in:97: warning: AC_TRY_RUN called without default to allow cross compiling
configure.in:98: warning: AC_TRY_RUN called without default to allow cross compiling
configure.in:99: warning: AC_TRY_RUN called without default to allow cross compiling
configure.in:100: warning: AC_TRY_RUN called without default to allow cross compiling
configure.in:101: warning: AC_TRY_RUN called without default to allow cross compiling
autoconf: Undefined macros:
***BUG in Autoconf--please report*** AC_PATH_TOOL

asdf install returned exit code 1

Action failed: asdf install
```

**Comment by nathany** [comment]
Seems to be using an autoconf wrapper on Ubuntu 12.04 (on CircleCI where I'm using asdf) that chooses which autoconf version. Not sure if the version of autoconf is the problem though.

I'm not familiar with autoconf and I'm sure the difference between `erlang 19.0` or `erlang ref:OTP-19.0.2` that results in this issue.
