### ISSUE TITLE
Observer not working, wxe_driver.so not found, macOS

### ISSUE THREAD

**Issue by vlttnv** [asdf-vm/asdf-erlang#176]
Hello,

I followed the instruction to install `wxmac` before installing erlang but unfortunately when trying to start the observer I still get `11:05:48.164 [error] ERROR: Could not find 'wxe_driver.so' in: /Users/valio/.asdf/installs/erlang/23.2.1/lib/wx-1.9.2/priv`

I have tried reinstalling multiple times. During the build process I see the following message:
```
APPLICATIONS INFORMATION (See: /Users/valio/.asdf/plugins/erlang/kerl-home/builds/asdf_23.2.1/otp_build_23.2.1.log)
 * wx             : No OpenGL headers found, wx will NOT be usable
 * No GLU headers (glu.h) found, wx will NOT be usable
```
I am not sure if this is relevant.

Is there a way to solve this?

**Comment by seivan** [comment]
@vlttnv Could you try this fork https://github.com/seivan/asdf-erlang/tree/feature/better_defaults and let me know if it works for you?

**Comment by Stratus3D** [comment]
Hi @vlttnv, sorry for the late reply here. Have you tried updating asdf-erlang to the latest version? (`asdf plugin-update erlang`)

Did you install wxmac via brew? If so, does `brew doctor` report any issues? It appears Erlang just can't find it, which leads me to believe either it didn't get installed or got installed but can't be found by Erlang (due to not being on the path, unlinked in brew, etc...).

**Comment by Stratus3D** [comment]
Closing due to lack of response.
