### ISSUE TITLE
[Question] How to enable erlang-history?

### ISSUE THREAD

**Issue by szymon-jez** [asdf-vm/asdf-erlang#30]
How can I enable [erlang-history](https://github.com/ferd/erlang-history) for all my Erlang instalations via asdf? To for e.g. [get command history in iex](https://stackoverflow.com/questions/22426716/how-to-save-log-the-output-of-the-iex-shell-to-get-persistent-command-history)?

I think that this might be worth pursuing to work OTB (by default or option).

**Comment by zackehh** [comment]
Once OTP 20 is installed, you can use `export ERL_AFLAGS="-kernel shell_history enabled"`.

**Comment by Stratus3D** [comment]
@szymon-jez installing erlang-history can be done by following the instructions in the erlang-history readme. asdf doesn't change anything other than the location of the Erlang install, so that's really the only thing you may have to modify. Use `asdf where erlang <vsn>` to find the directory your Erlang version is installed in.

Please reopen this ticket if you any encounter any issues. Also feel free to create a wiki page with this info.
