### ISSUE TITLE
Combine asdf-erlang and asdf-kerl?

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf-erlang#53]
Today I switched to the excellent asdf-kerl, and was able to install Erlang with wx support. Using asdf-kerl I noticed a couple things, and I thought maybe it would be wise to rethink how we write asdf plugins. I think starting with a blank slate, as we did with asdf-erlang, wasn't ideal. Building on the work of others, as was done with asdf-kerl, allows us to leverage a lot of previous trial and error. So, I think asdf-kerl should become asdf-erlang. But, I did notice a few issues with both asdf-kerl and asdf-erlang:

asdf-erlang:
* You are on your own when it comes to patches. You'll need to figure out which ones you need for your OS and Erlang version
* Minimal support for different OSes, you might end up needing to specify a lot of custom paths on OSes like Mac OSX.

asdf-kerl:
* App specific binaries aren't on the $PATH (fixed this in asdf-erlang here: https://github.com/asdf-vm/asdf-erlang/commit/a68a642edaf7c2ad53889f52ab4628cb191d775f)
* Doesn't automatically update the list of available versions that kerl knows about when using the `list-all` command. Seems like we just need to spend a few more minutes on the shell script to iron out some issues.
* Docs are unclear if it installs kerl or expects kerl to be present

What do you think @HashNuke @eproxus @asdf-vm/maintainers ?

Many of these things apply to https://github.com/asdf-vm/asdf-ruby/pull/51 as well.

**Comment by eproxus** [comment]
I am all for it, but I do not want to impose anything on this project. My current implementation of [_asdf-kerl_](https://github.com/eproxus/asdf-kerl) is a minimal viable product that worked for me, with minor touchups added when people started using it.

Currently, _kerl_ is not automatically installed by _asdf-kerl_. This could be done in the plug-in, cloning _kerl_ the first time the plug-in is used for example. The same goes for updating the list of Erlang releases when calling `list-all`.

Regarding the app specific binaries, it might be a matter of taste. I think _kerl_ runs `make install` which installs Erlang with the default set of files, directories and binaries. Either we propose to _kerl_ to do this linking upstream, or we add it to _asdf-kerl_ as well.

There is the added complexity of _kerl_ knowing about each install via _asdf-kerl_ since its state is global (based on the `.kerl` directory). If a user installs _kerl_ separately, installs should be isolated if possible. _kerl_ does not have any functionality today to do this.

**Comment by Stratus3D** [comment]
It actually looks like https://github.com/tuvistavie/asdf-python already does something like this with py-env. It seems like asdf-python downloads py-env itself, in place it can execute from, and then when installing versions of python it just makes sure it has already installed py-env.
