### ISSUE TITLE
How to install versions of erlang from git?

### ISSUE THREAD

**Issue by enilsen16** [asdf-vm/asdf-erlang#59]
Before the change to using `kerl` you were able to do something like `asdf install erlang ref:maint` and this no longer works.

With the change to using kerl, what's the best way to install erlang from master?

**Comment by Stratus3D** [comment]
Unfortunately this isn't supported by asdf-erlang right now. kerl does have support for this, but we aren't handling `ref:` versions correctly in asdf-erlang. We need to update the install script so it executes `kerl build git ...` rather than `kerl build <version>` when an `ref:` version is encountered.

**Comment by shymega** [comment]
What would be a good way to approach this?

I can submit a PR, but I'm not sure what way would be ideal, or idiomatic.

cc/ @Stratus3D

**Comment by Stratus3D** [comment]
@shymega PR would be welcome. I need to go back and look at the details on what kerl requires to do this, but I think we may only need an if statement in the plugin code when we invoke `kerl build`.

**Comment by shymega** [comment]
@Stratus3D So that'd be in the `install_erlang` function, right? I suppose we could set `$ASDF_INSTALL_VERSION` to a Git reference, or a pre-defined version, but I'd like to consider validation as well - any thoughts on that?

**Comment by Stratus3D** [comment]
Fixed by #69
